"""empty message

Revision ID: 028a8269002d
Revises: 6f87b2d35210
Create Date: 2020-05-29 17:33:20.766414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028a8269002d'
down_revision = '6f87b2d35210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchantID', sa.Integer(), nullable=True),
    sa.Column('queueID', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=500), nullable=True),
    sa.Column('waitTime', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('lines', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lines', 'count')
    op.drop_table('customers')
    # ### end Alembic commands ###
