"""empty message

Revision ID: 20d50fd06874
Revises: decab81c9b5a
Create Date: 2020-05-30 04:21:01.223991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d50fd06874'
down_revision = 'decab81c9b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchantID', sa.Integer(), nullable=True),
    sa.Column('customerID', sa.Integer(), nullable=True),
    sa.Column('messages', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('merchantID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customerID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('messages', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='chats_pkey')
    )
    op.drop_table('chatts')
    # ### end Alembic commands ###
