"""empty message

Revision ID: 22439ade22a6
Revises: 028a8269002d
Create Date: 2020-05-29 19:58:30.202774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22439ade22a6'
down_revision = '028a8269002d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'merchants', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'merchants', type_='unique')
    # ### end Alembic commands ###
