"""empty message

Revision ID: 310cebb3909a
Revises: 22439ade22a6
Create Date: 2020-05-30 02:39:17.515673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310cebb3909a'
down_revision = '22439ade22a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchantID', sa.Integer(), nullable=True),
    sa.Column('customerID', sa.Integer(), nullable=True),
    sa.Column('messages', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chats')
    # ### end Alembic commands ###
