"""empty message

Revision ID: 514be2c7ed85
Revises: d2ae07d93860
Create Date: 2020-05-29 10:22:32.949174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '514be2c7ed85'
down_revision = 'd2ae07d93860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('merchants_email_key', 'merchants', type_='unique')
    op.drop_column('merchants', 'creation_date')
    op.drop_column('merchants', 'image')
    op.drop_column('merchants', 'email')
    op.drop_column('merchants', 'biography')
    op.drop_column('merchants', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('merchants', sa.Column('biography', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('merchants', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('merchants', sa.Column('image', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('merchants', sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_unique_constraint('merchants_email_key', 'merchants', ['email'])
    # ### end Alembic commands ###
